# Generated by Django 6.0.5 on 2026-05-06 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rolepermission_remove_business_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_otp_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='otp_resend_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='type',
            field=models.CharField(choices=[('email_verify', 'Email Verification'), ('password_reset', 'Password Reset')], max_length=20),
        ),
    ]
