# Generated by Django 6.0 on 2026-05-15 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calllog',
            name='duration',
            field=models.CharField(blank=True, help_text='Duration of the call (e.g., 02:30)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='status',
            field=models.CharField(blank=True, help_text='Status decided by AI', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='transcript',
            field=models.JSONField(blank=True, help_text='Conversation transcript in array format', null=True),
        ),
    ]
