# Generated by Django 6.0.5 on 2026-05-08 19:58

import apps.configuration.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('openai_key', apps.configuration.models.EncryptedTextField(blank=True, null=True)),
                ('deepgram_key', apps.configuration.models.EncryptedTextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='api_config', to='accounts.business')),
            ],
            options={
                'verbose_name': 'API Config',
                'verbose_name_plural': 'API Configs',
            },
        ),
        migrations.CreateModel(
            name='CRMConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('gohighlevel', 'GoHighLevel'), ('hubspot', 'HubSpot'), ('zoho', 'Zoho'), ('salesforce', 'Salesforce'), ('other', 'Other')], default='gohighlevel', max_length=50)),
                ('token', apps.configuration.models.EncryptedTextField(blank=True, help_text='API token / OAuth token', null=True)),
                ('location_id', apps.configuration.models.EncryptedTextField(blank=True, help_text='CRM Location / Account ID', null=True)),
                ('webhook_secret', apps.configuration.models.EncryptedTextField(blank=True, help_text='Webhook signing secret', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crm_config', to='accounts.business')),
            ],
            options={
                'verbose_name': 'CRM Config',
                'verbose_name_plural': 'CRM Configs',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Friendly display name', max_length=255)),
                ('file', models.FileField(help_text='Accepted: pdf, json, csv, txt, docx', upload_to='knowledge_files/')),
                ('file_type', models.CharField(blank=True, help_text='Auto-detected from file extension', max_length=20)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Populated when status=failed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_files', to='accounts.business')),
            ],
            options={
                'verbose_name': 'Knowledge File',
                'verbose_name_plural': 'Knowledge Files',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TwilioConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('twilio_sid', apps.configuration.models.EncryptedTextField(blank=True, help_text='Twilio Account SID', null=True)),
                ('twilio_token', apps.configuration.models.EncryptedTextField(blank=True, help_text='Twilio Auth Token', null=True)),
                ('twilio_number', models.CharField(blank=True, help_text='Outbound caller ID, e.g. +1234567890', max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='twilio_config', to='accounts.business')),
            ],
            options={
                'verbose_name': 'Twilio Config',
                'verbose_name_plural': 'Twilio Configs',
            },
        ),
        migrations.CreateModel(
            name='VoiceConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('neutral', 'Neutral')], default='female', max_length=20)),
                ('tone', models.CharField(choices=[('professional', 'Professional'), ('friendly', 'Friendly'), ('formal', 'Formal'), ('casual', 'Casual')], default='professional', max_length=20)),
                ('voice_template', models.FileField(blank=True, help_text='Optional audio sample file (mp3/wav)', null=True, upload_to='voice_templates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voice_config', to='accounts.business')),
            ],
            options={
                'verbose_name': 'Voice Config',
                'verbose_name_plural': 'Voice Configs',
            },
        ),
    ]
